version: "3"

services:
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
  node-app:
    image: koushiksiri48/docker-node-node-app
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=koushik
      - MONGO_PASSWORD=krishna
      - SESSION_SECRET=secret
    command: node index.js
  mongo:
    image: mongo:latest    
    environment:
      - MONGO_INITDB_ROOT_USERNAME=koushik
      - MONGO_INITDB_ROOT_PASSWORD=krishna